name: VM Publish Production

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env    
      
      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run eslint

      - name: Build static files
        run: npm run build    

      - name: Build sitemap
        run: npm run sitemap
      
      - name: Remove .env file
        run: rm .env
  
  test:
    needs: 
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env    

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Remove .env file
        run: rm .env

  deploy-to-vm:
    needs: 
      - build
      - test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Create .env file
      run: echo "${{ secrets.ENV_FILE }}" > .env

    - name: SSH and Remove old files
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          rm -rf ${{ secrets.SERVER_LOCATION }}/github/workspace
    
    - name: SCP files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: "${{ secrets.SERVER_HOST }}"
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "${{ github.workspace }}"
        target: "${{ secrets.SERVER_LOCATION }}"
    
    - name: SSH and Docker build
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ${{ secrets.SERVER_LOCATION }}/github/workspace
          docker build -t ${{ secrets.IMAGE_NAME }}:${{ secrets.IMAGE_TAG }} .
          docker-compose -f compose-local-image.yml down
          docker-compose -f compose-local-image.yml up -d
          docker image prune -f

  deploy-to-docker-hub:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "VITE_DEBUG=true" > .env
          echo "VITE_CLIENT_URL=http://localhost:5173" >> .env
          echo "VITE_API_URL=http://localhost:3000" >> .env
          echo "VITE_WS_URL=ws://localhost:3001" >> .env
          echo "VITE_API_PREFIX=/api/v1/mysql" >> .env
          echo "VITE_AUTH_LS_KEY=chat-auth-token" >> .env
          echo "VITE_ENVIRONMENT=development" >> .env
          echo "VITE_ROLLBAR_CLIENT_ITEM_ACCESS_TOKEN=secret" >> .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/chat-app:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/chat-app:latest ${{ secrets.DOCKER_USERNAME }}/chat-app:${{ github.sha }}

      - name: Push image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/chat-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/chat-app:${{ github.sha }}